# Generated by Django 5.0.1 on 2024-01-17 18:20

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_authuser_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(default='10224761ff1f298b33c9d9022f1de15a3bf2c5b3ba1625a38e695aacd5784c57', max_length=64, null=True)),
                ('expires_at', models.DateTimeField(default=datetime.datetime(2024, 1, 17, 18, 30, 21, 189037, tzinfo=datetime.timezone.utc))),
                ('activated_at', models.DateTimeField(default=None, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='activation', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
