# Generated by Django 5.0.1 on 2024-01-23 18:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_activation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activation',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 23, 18, 27, 1, 280461, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='activation',
            name='token',
            field=models.CharField(default=None, max_length=64, null=True, unique=True),
        ),
    ]
