# Generated by Django 5.0.1 on 2024-01-24 18:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Ingredients')),
                ('image', models.ImageField(default=None, upload_to='ingredients/', verbose_name='Ingredient Image')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('data', models.JSONField(null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Store Name')),
                ('description', models.TextField(verbose_name='Store Description')),
                ('logo', models.ImageField(default=None, upload_to='stores/', verbose_name='Store Image')),
                ('delivery_fee', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Delivery Fee')),
                ('profit_fee', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Profit Fee')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stores', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Pizza Name')),
                ('image', models.ImageField(default=None, upload_to='pizza/', verbose_name='Pizza Image')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pizza', to='stores.store')),
            ],
            options={
                'verbose_name': 'pizza',
                'verbose_name_plural': 'pizza',
            },
        ),
        migrations.CreateModel(
            name='StoreIngredients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stock', models.IntegerField(default=0)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='stores.ingredient')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stores.store')),
            ],
            options={
                'verbose_name': 'store_ingredient',
                'verbose_name_plural': 'store_ingredients',
            },
        ),
        migrations.AddField(
            model_name='store',
            name='ingredients',
            field=models.ManyToManyField(related_name='stores', through='stores.StoreIngredients', to='stores.ingredient'),
        ),
        migrations.CreateModel(
            name='PizzaIngredients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.IntegerField(default=0)),
                ('pizza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stores.pizza')),
                ('store_ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stores.storeingredients')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='pizza',
            name='ingredients',
            field=models.ManyToManyField(related_name='pizza', through='stores.PizzaIngredients', to='stores.storeingredients'),
        ),
    ]
