# Generated by Django 5.0.1 on 2024-02-11 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='storeingredients',
            options={'verbose_name': 'store ingredient', 'verbose_name_plural': 'store ingredient'},
        ),
        migrations.AlterField(
            model_name='pizza',
            name='image',
            field=models.ImageField(upload_to='pizza/', verbose_name='Pizza Image'),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Pizza Name'),
        ),
        migrations.AlterField(
            model_name='pizzaingredients',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
